import { Playfair_Display, Poppins } from "next/font/google";

const playfair = Playfair_Display({ subsets: ["latin"], weight: "700", variable: "--font-playfair"});


const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"], variable: "--font-poppins" });


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`
    ${geistSans.variable}
    ${geistMono.variable}
    ${poppins.variable}
    ${playfair.variable}
    antialiased
    bg-[#fdf8f1]
    text-[#1e1e1e]
  `}
>
  {children}
</body>

    </html>
  );
}
